---
title: "Life Expectancy at Birth (LEB) of Different Country"
author: "qingcheng"
date: "Sunday, August 24, 2014"
output: html_document
---

## Introduction and Motivation
**Life Expectancy at Birth (LEB)** is the expected (in the statistical sense) number of years of life remaining at birth. There are great variations in life expectancy between different parts of the world, mostly caused by differences in 

> * Economic circumstances
> * Public health
> * Medical care 
> * Industrial pollution

The impact of AIDS is particularly notable on life expectancy in many African countries. The difference in life expectancy between men and women is also obvious. Therefore, we build this **Shiny App** to show the LEB of different country and gender.


## Instructions
The user is required to select gender and country.Then the user needs to press the GO button, so the main panel is populated with the available data. The main panel is consist of 3 tabs:

#### 1. Mean value
This will show you the **Mean LEB value of recent year** of the gender and country been selected, and the picture below show the great variations in life expectancy between different parts of the world by color.


#### 2. Data Summary
This tab will list the exact LEB value (years) in different year.


#### 3. Plot: Mean LEB Trend
This tab show the plot(rCharts) of the trend of LEB estimates for both genders in time.

The data is come from [WHO Global Health Observatory Data Repository][1] and [KNOEMA-World Development Indicators (WDI) Database][2]. The time data downloaded is:

[1] "Sat Aug 23 18:31:18 2014"

Feel free to send me your comments,questions or report bugs [xiang_lqc at 126.com].

[1]:http://apps.who.int/gho/data/view.main.680?lang=en
[2]:http://cn.knoema.com/WBWDIGDF2014Jul/world-development-indicators-wdi-july-2014